import Link from 'next/link';
import { auth } from '../../../auth';
import { db } from '../../../lib/db';
import StoreHeader from '../../../components/store-header';

export default async function OrdersPage() {
 const session=await auth();
 if(session?.user?.role!=='customer'||!session.user.email)return <main className="store-dark min-h-screen"><StoreHeader/><div className="container py-16"><div className="zenvora-empty-state mx-auto max-w-lg"><h1 className="text-2xl font-black">Sign in to view your orders</h1><Link href="/login?callbackUrl=/account/orders" className="mt-6 inline-flex rounded-xl bg-violet-700 px-6 py-3 font-black text-white">Sign in</Link></div></div></main>;
 const orders=await db.order.findMany({where:{email:session.user.email,deletedAt:null},orderBy:{createdAt:'desc'},take:50,select:{orderNumber:true,status:true,totalAmount:true,createdAt:true,items:{select:{productName:true,quantity:true},take:4}}});
 return <main className="store-dark min-h-screen pb-28 sm:pb-10"><StoreHeader loggedIn/><div className="container py-8 sm:py-10"><div className="zenvora-page-hero"><div><span className="inline-flex rounded-full border bg-violet-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-violet-700">Purchase history</span><h1 className="mt-4 text-4xl font-black tracking-[-.04em]">My orders</h1><p className="mt-3 text-sm text-slate-500">View status, payment and delivery progress for your purchases.</p></div></div><div className="mt-7 space-y-3">{orders.map(o=><article key={o.orderNumber} className="zenvora-order-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black text-violet-700">{o.orderNumber}</p><h2 className="mt-1 text-lg font-black text-slate-900">₹{Number(o.totalAmount).toLocaleString('en-IN',{minimumFractionDigits:2})}</h2><p className="mt-1 text-xs text-slate-500">{new Date(o.createdAt).toLocaleDateString('en-IN')}</p></div><span className="rounded-full bg-violet-50 px-3 py-1.5 text-[10px] font-black uppercase text-violet-700">{o.status.replaceAll('_',' ')}</span></div><p className="mt-4 text-sm text-slate-600">{o.items.map(i=>i.productName+' × '+i.quantity).join(' · ')}</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/track-order" className="rounded-xl bg-violet-700 px-4 py-2.5 text-xs font-black text-white">Track order</Link><Link href={'/payment/'+o.orderNumber} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-600">Payment</Link></div></article>)}{!orders.length&&<div className="zenvora-empty-state"><p className="font-black">No orders yet</p><Link href="/products" className="mt-4 inline-flex rounded-xl bg-violet-700 px-5 py-3 text-xs font-black text-white">Start shopping</Link></div>}</div></div></main>;
}
