'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Permission={key:string;label:string;description:string};
type Staff={id:string;email:string;accessRole:string;permissions:string[];isActive:boolean;createdAt:string};

export default function StaffPage(){
 const [staff,setStaff]=useState<Staff[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [selected,setSelected]=useState<string[]>(['products','pricing','images','inventory']); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/staff');const j=await r.json();if(!r.ok)throw new Error(j.error);setStaff(j.staff);setPermissions(j.permissions)}catch(e){setError(e instanceof Error?e.message:'Unable to load staff.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const toggle=(key:string)=>setSelected(x=>x.includes(key)?x.filter(k=>k!==key):[...x,key]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');setSaving(true);try{const r=await fetch('/api/admin/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,permissions:selected})});const j=await r.json();if(!r.ok)throw new Error(j.error);setEmail('');setPassword('');setMessage('Staff account created successfully.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create staff.')}finally{setSaving(false)}};
 const update=async(id:string,data:Record<string,unknown>)=>{setError('');try{const r=await fetch('/api/admin/staff',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...data})});const j=await r.json();if(!r.ok)throw new Error(j.error);setStaff(x=>x.map(s=>s.id===id?j.staff:s))}catch(e){setError(e instanceof Error?e.message:'Unable to update staff.')}};
 return <main className="min-h-screen bg-slate-100"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="container flex min-h-16 items-center justify-between gap-3"><Link href="/admin/dashboard" className="text-xl font-black">zenvora<span className="text-indigo-600">.</span><span className="ml-2 text-xs uppercase tracking-widest text-slate-400">Admin</span></Link><Link href="/admin/dashboard" className="rounded-xl px-3 py-2 text-sm font-bold">← Dashboard</Link></div></header>
 <div className="container py-6 sm:py-8"><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Access control</p><h1 className="mt-1 text-3xl font-black">Staff & permissions</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Create separate staff logins and give each person only the store permissions they need. Your super-admin account keeps full access.</p>
 {error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</div>}
 <div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]">
 <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Create staff account</h2><form onSubmit={create} className="mt-4 space-y-4"><label className="block text-sm font-bold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border px-3" placeholder="staff@zenvora.in"/></label><label className="block text-sm font-bold">Temporary password<input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border px-3" placeholder="At least 12 characters"/><span className="mt-1 block text-[11px] font-normal text-slate-500">Give the staff member this password securely; they can use the admin login.</span></label><div><p className="text-sm font-bold">Permissions</p><div className="mt-2 space-y-2">{permissions.map(p=><label key={p.key} className="flex cursor-pointer gap-3 rounded-xl border p-3 hover:bg-slate-50"><input type="checkbox" checked={selected.includes(p.key)} onChange={()=>toggle(p.key)} className="mt-1"/><span><b className="block text-sm">{p.label}</b><span className="text-xs text-slate-500">{p.description}</span></span></label>)}</div></div><button disabled={saving} className="h-12 w-full rounded-xl bg-slate-900 font-black text-white disabled:opacity-50">{saving?'Creating…':'Create staff account'}</button></form></section>
 <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">Staff accounts</h2><span className="text-xs text-slate-500">{staff.length} account{staff.length===1?'':'s'}</span></div>{loading?<div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500">Loading…</div>:<div className="space-y-3">{staff.map(s=><article key={s.id} className="rounded-2xl bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black">{s.email}</p><p className="mt-1 text-xs text-slate-500">{s.accessRole==='SUPER_ADMIN'?'Super administrator':'Staff'} · Created {new Date(s.createdAt).toLocaleDateString('en-IN')}</p></div><button onClick={()=>update(s.id,{isActive:!s.isActive})} className={`rounded-full px-3 py-1 text-xs font-bold ${s.isActive?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{s.isActive?'Active':'Disabled'}</button></div><div className="mt-4 flex flex-wrap gap-2">{permissions.filter(p=>s.permissions?.includes(p.key)).map(p=><span key={p.key} className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{p.label}</span>)}</div>{s.accessRole!=='SUPER_ADMIN'&&<div className="mt-4 border-t pt-4"><p className="mb-2 text-xs font-bold text-slate-500">Quick permission controls</p><div className="flex flex-wrap gap-2">{permissions.map(p=><button key={p.key} onClick={()=>update(s.id,{permissions:s.permissions.includes(p.key)?s.permissions.filter(x=>x!==p.key):[...s.permissions,p.key]})} className={`rounded-lg border px-2.5 py-1.5 text-xs font-bold ${s.permissions.includes(p.key)?'border-indigo-200 bg-indigo-50 text-indigo-700':'text-slate-500'}`}>{p.label}</button>)}</div></div>}</article>)}</div>}</section></div></div></main>;
}