'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import AdminNav from '../../../../components/admin-nav';
type Collection={id:string;title:string;handle:string;productsCount:number};
type Category={id:string;name:string;slug:string};
export default function CategoryMappingPage(){
 const [collections,setCollections]=useState<Collection[]>([]),[categories,setCategories]=useState<Category[]>([]),[mappings,setMappings]=useState<Record<string,string>>({}),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{(async()=>{try{const [a,b]=await Promise.all([fetch('/api/admin/marketplaces/category-mappings'),fetch('/api/admin/marketplaces/shopify/collections')]);const aj=await a.json(),bj=await b.json();if(!a.ok)throw new Error(aj.error||'Unable to load mappings.');if(!b.ok)throw new Error(bj.error||'Unable to load Shopify collections.');setMappings(aj.mappings||{});setCategories(aj.categories||[]);setCollections(bj.collections||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load mappings.')}finally{setBusy(false)}})()},[]);
 const save=async()=>{setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/admin/marketplaces/category-mappings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({mappings})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed.');setMappings(j.mappings||{});setMessage('Category mappings saved. Automatic and controlled imports will use them.')}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setSaving(false)}};
 return <main className="min-h-screen bg-slate-950 text-slate-100"><AdminNav active="marketplaces"/><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-400">Shopify</p><h1 className="mt-1 text-3xl font-black">Category Mapping</h1><p className="mt-2 text-sm text-slate-400">Map Shopify collections to your Zenvora categories instead of creating categories from source names.</p></div><Link href="/admin/marketplaces" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold">← Marketplace Center</Link></div>
 {error&&<div className="mt-5 rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{message&&<div className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-sm text-emerald-300">{message}</div>}
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Collection mappings</h2><p className="mt-1 text-xs text-slate-500">Unmapped collections keep the existing automatic category fallback.</p></div><button disabled={busy||saving} onClick={save} className="rounded-xl bg-white px-5 py-3 text-xs font-black text-slate-950 disabled:opacity-40">{saving?'Saving…':'Save mappings'}</button></div>
 <div className="mt-5 space-y-2">{collections.map(c=><div key={c.id} className="grid gap-3 rounded-2xl border border-white/10 bg-black/10 p-4 sm:grid-cols-[1fr_1fr] sm:items-center"><div><b className="block">{c.title}</b><span className="text-[10px] text-slate-500">{c.handle} · {c.productsCount} products</span></div><select value={mappings[c.handle]||''} onChange={e=>setMappings(v=>{const n={...v};if(e.target.value)n[c.handle]=e.target.value;else delete n[c.handle];return n})} className="h-11 rounded-xl border border-white/10 bg-slate-900 px-3 text-sm"><option value="">Automatic fallback</option>{categories.map(ca=><option key={ca.id} value={ca.id}>{ca.name}</option>)}</select></div>)}{!collections.length&&!busy&&<p className="py-8 text-center text-sm text-slate-500">No Shopify collections returned.</p>}</div></section></div></main>;
}