'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Approval={id:string;requestedBy:string;action:string;entityType:string;entityId:string|null;payload:Record<string,unknown>;createdAt:string};

export default function ApprovalsPage(){
 const [items,setItems]=useState<Approval[]>([]);const [forbidden,setForbidden]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);const r=await fetch('/api/admin/approvals');const j=await r.json();if(r.status===403){setForbidden(true);setLoading(false);return}setItems(j.approvals||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const decide=async(id:string,decision:'APPROVE'|'REJECT')=>{setBusy(id);try{const r=await fetch('/api/admin/approvals',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,decision})});const j=await r.json();if(!r.ok)throw new Error(j.error);setItems(x=>x.filter(a=>a.id!==id));}catch(e){alert(e instanceof Error?e.message:'Unable to process')}finally{setBusy('')}};
 return <main className="min-h-screen bg-slate-100"><header className="sticky top-0 z-30 border-b bg-white"><div className="container flex min-h-16 items-center justify-between"><Link href="/admin/dashboard" className="text-xl font-black">zenvora<span className="text-indigo-600">.</span><span className="ml-2 text-xs uppercase tracking-widest text-slate-400">Owner</span></Link><Link href="/admin/dashboard" className="rounded-xl px-3 py-2 text-sm font-bold">← Dashboard</Link></div></header><div className="container py-8">{forbidden?<div className="rounded-2xl bg-white p-8 text-center"><h1 className="text-xl font-black">Super administrator access required</h1></div>:<><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Owner control</p><h1 className="mt-1 text-3xl font-black">Approvals</h1><p className="mt-2 text-sm text-slate-500">Review sensitive changes requested by staff before they reach the store.</p><div className="mt-6 space-y-3">{loading?<div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500">Loading…</div>:items.length===0?<div className="rounded-2xl bg-white p-8 text-center"><p className="font-black">No pending approvals</p><p className="mt-1 text-sm text-slate-500">Sensitive staff requests will appear here.</p></div>:items.map(a=><article key={a.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-black">{a.action.replaceAll('_',' ')}</p><p className="mt-1 text-sm text-slate-500">{a.entityType} · Requested by {a.requestedBy}</p><p className="mt-1 text-xs text-slate-400">{new Date(a.createdAt).toLocaleString('en-IN')}</p></div><div className="flex gap-2"><button disabled={busy===a.id} onClick={()=>decide(a.id,'REJECT')} className="rounded-xl border px-4 py-2 text-sm font-bold">Reject</button><button disabled={busy===a.id} onClick={()=>decide(a.id,'APPROVE')} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Approve</button></div></div><pre className="mt-4 overflow-auto rounded-xl bg-slate-50 p-3 text-xs">{JSON.stringify(a.payload,null,2)}</pre></article>)}</div></>}</div></main>;
}
