'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { signIn } from 'next-auth/react';

export default function Login() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);const r=await signIn('credentials',{email,password,redirect:false,callbackUrl:'/admin/dashboard'});if(r?.error){setError('Invalid email or password.');setLoading(false);return;}window.location.href=r?.url||'/admin/dashboard';}
  return <main className="min-h-screen bg-slate-950 px-5 py-10"><div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-5xl items-center justify-center"><div className="grid w-full overflow-hidden rounded-3xl bg-white shadow-2xl md:grid-cols-2">
    <div className="hidden bg-indigo-600 p-10 text-white md:flex md:flex-col md:justify-between"><Link href="/" className="text-2xl font-black">zenvora<span className="text-indigo-200">.</span></Link><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-200">Secure admin</p><h1 className="mt-3 text-4xl font-black">Manage your store from one place.</h1><p className="mt-4 leading-7 text-indigo-100">Products, orders and payment settings are protected behind administrator authentication.</p></div><p className="text-xs text-indigo-200">Administrator access only</p></div>
    <div className="p-7 sm:p-10"><Link href="/" className="text-sm font-semibold text-slate-500 hover:text-slate-900">← Back to store</Link><div className="mt-10"><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Zenvora Admin</p><h2 className="mt-2 text-3xl font-black text-slate-950">Welcome back</h2><p className="mt-2 text-sm text-slate-500">Sign in to manage your store.</p></div>
    <form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-bold text-slate-700">Email<input required autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" placeholder="admin@example.com"/></label><label className="block text-sm font-bold text-slate-700">Password<input required autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" placeholder="••••••••"/></label>{error&&<div role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}<button disabled={loading} className="w-full rounded-xl bg-slate-950 py-3.5 font-bold text-white hover:bg-slate-800 disabled:opacity-60">{loading?'Signing in…':'Sign in to dashboard'}</button></form></div>
  </div></div></main>;
}