'use client';
import {useMemo,useState} from 'react';
const money=(v:string|number)=>'₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const empty:any={name:'Global 20%',scope:'GLOBAL',provider:'',categoryId:'',markupPercent:'20',fixedAmount:'0',minPrice:'',maxPrice:'',roundingMode:'NONE',enabled:true,priority:'0'};
export default function PricingAdmin({initialRules,initialCategories,initialProducts}:{initialRules:any[];initialCategories:any[];initialProducts:any[]}){
 const [rules,setRules]=useState(initialRules),[products,setProducts]=useState(initialProducts),[form,setForm]=useState<any>(empty),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[message,setMessage]=useState('');
 const visible=useMemo(()=>products.filter(p=>!filter||p.name.toLowerCase().includes(filter.toLowerCase())),[products,filter]);
 const saveRule=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error);setRules((x:any[])=>[j.rule,...x]);setForm({...empty});setMessage('Pricing rule added.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}};
 const remove=async(id:string)=>{if(!confirm('Delete this pricing rule?'))return;const r=await fetch('/api/admin/pricing',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)setRules((x:any[])=>x.filter(a=>a.id!==id))};
 const apply=async()=>{if(!confirm('Recalculate prices for all products with source cost?'))return;setBusy(true);setMessage('Recalculating…');try{const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'apply'})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMessage('Updated '+j.updatedCount+' products. Locked: '+j.skippedLocked+'. Missing source cost: '+j.skippedNoSource+'.');location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Unable to recalculate')}finally{setBusy(false)}};
 const lock=async(p:any)=>{const raw=prompt('Locked selling price (leave blank to lock current price):',p.sellingPrice);if(raw===null)return;const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'lock',productId:p.id,price:raw})});const j=await r.json();if(!r.ok){alert(j.error);return}setProducts((x:any[])=>x.map(a=>a.id===p.id?{...a,priceLocked:true,priceLockValue:String(j.product.priceLockValue)}:a))};
 const unlock=async(p:any)=>{const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unlock',productId:p.id})});if(r.ok)setProducts((x:any[])=>x.map(a=>a.id===p.id?{...a,priceLocked:false,priceLockValue:null}:a))};
 return <div className="mt-8 space-y-6">
 <section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Automatic pricing</h2><p className="mt-1 text-sm text-slate-500">Source cost + markup + optional fixed amount, limits and rounding.</p></div><button disabled={busy} onClick={apply} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Recalculate all</button></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="rounded-xl border px-3 py-3" placeholder="Rule name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="rounded-xl border px-3 py-3" value={form.scope} onChange={e=>setForm({...form,scope:e.target.value,provider:'',categoryId:''})}><option value="GLOBAL">Global</option><option value="MARKETPLACE">Marketplace</option><option value="CATEGORY">Category</option></select>{form.scope==='MARKETPLACE'?<select className="rounded-xl border px-3 py-3" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="">Select marketplace</option><option>AMAZON</option><option>FLIPKART</option><option>MEESHO</option></select>:form.scope==='CATEGORY'?<select className="rounded-xl border px-3 py-3" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Select category</option>{initialCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:<div/>}<input className="rounded-xl border px-3 py-3" type="number" step="0.01" placeholder="Markup %" value={form.markupPercent} onChange={e=>setForm({...form,markupPercent:e.target.value})}/><input className="rounded-xl border px-3 py-3" type="number" step="0.01" placeholder="Fixed ₹" value={form.fixedAmount} onChange={e=>setForm({...form,fixedAmount:e.target.value})}/><input className="rounded-xl border px-3 py-3" type="number" placeholder="Minimum price" value={form.minPrice} onChange={e=>setForm({...form,minPrice:e.target.value})}/><input className="rounded-xl border px-3 py-3" type="number" placeholder="Maximum price" value={form.maxPrice} onChange={e=>setForm({...form,maxPrice:e.target.value})}/><select className="rounded-xl border px-3 py-3" value={form.roundingMode} onChange={e=>setForm({...form,roundingMode:e.target.value})}><option value="NONE">No rounding</option><option value="UP_TO_10">Round up to ₹10</option><option value="UP_TO_50">Round up to ₹50</option><option value="UP_TO_100">Round up to ₹100</option><option value="NEAREST_10">Nearest ₹10</option><option value="NEAREST_50">Nearest ₹50</option><option value="NEAREST_100">Nearest ₹100</option></select><input className="rounded-xl border px-3 py-3" type="number" placeholder="Priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}/></div>
 <div className="mt-4 flex flex-wrap items-center gap-3"><button disabled={busy} onClick={saveRule} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">{busy?'Saving…':'Add pricing rule'}</button>{message&&<span className="text-sm font-semibold text-slate-600">{message}</span>}</div>
 <div className="mt-6 space-y-2">{rules.map((r:any)=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>{r.name}</b><span className="ml-2 text-xs text-slate-500">{r.scope}{r.provider?' · '+r.provider:''}{r.category?.name?' · '+r.category.name:''}</span></div><div className="flex items-center gap-3"><span className="font-black">+{r.markupPercent}%</span>{Number(r.fixedAmount)>0&&<span>+{money(r.fixedAmount)}</span>}<button onClick={()=>remove(r.id)} className="rounded-lg border px-3 py-1 text-sm">Delete</button></div></div>)}</div></section>
 <section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Product pricing & locks</h2><p className="text-sm text-slate-500">Locked prices are never changed by automatic recalculation.</p></div><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search products" className="rounded-xl border px-3 py-2"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Product</th><th className="p-3">Source cost</th><th className="p-3">Current price</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{visible.map((p:any)=><tr key={p.id} className="border-b last:border-0"><td className="p-3"><b>{p.name}</b><div className="text-xs text-slate-500">{p.category?.name||'Uncategorized'}</div></td><td className="p-3">{p.sourceCost?money(p.sourceCost):'—'}</td><td className="p-3 font-bold">{money(p.sellingPrice)}{p.priceLocked&&<div className="text-xs text-amber-700">Locked at {money(p.priceLockValue||p.sellingPrice)}</div>}</td><td className="p-3">{p.priceLocked?'🔒 Locked':'Automatic'}</td><td className="p-3">{p.priceLocked?<button onClick={()=>unlock(p)} className="rounded-lg border px-3 py-2 font-semibold">Unlock</button>:<button onClick={()=>lock(p)} className="rounded-lg bg-slate-900 px-3 py-2 font-semibold text-white">Lock price</button>}</td></tr>)}</tbody></table></div></section></div>
}