'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Address={id:string;label:string;fullName:string;phone:string;addressLine1:string;addressLine2:string|null;landmark:string|null;city:string;district:string;state:string;pinCode:string;isDefault:boolean};
const empty={label:'Home',fullName:'',phone:'',addressLine1:'',addressLine2:'',landmark:'',city:'',district:'',state:'',pinCode:'',isDefault:false};

export default function Addresses(){
  const [addresses,setAddresses]=useState<Address[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  async function load(){try{const r=await fetch('/api/account/addresses');const d=await r.json();if(!r.ok){setError(d.error||'Unable to load addresses.');return;}setAddresses(d.addresses||[]);}catch{setError('Unable to load addresses.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  function edit(a:Address){setEditing(a.id);setForm({...a,addressLine2:a.addressLine2||'',landmark:a.landmark||''});setError('');setMessage('');window.scrollTo({top:0,behavior:'smooth'});}
  function reset(){setEditing(null);setForm({...empty,isDefault:addresses.length===0});setError('');}
  async function save(e:React.FormEvent){e.preventDefault();setError('');setMessage('');setSaving(true);try{const r=await fetch('/api/account/addresses',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{...form,id:editing}:form)});const d=await r.json();if(!r.ok){setError(d.error||'Unable to save address.');return;}await load();reset();setMessage(editing?'Address updated successfully.':'Address saved successfully.')}catch{setError('Unable to save address.')}finally{setSaving(false)}}
  async function makeDefault(id:string){setError('');try{const a=addresses.find(x=>x.id===id);if(!a)return;const r=await fetch('/api/account/addresses',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,isDefault:true})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to set default address.');return;}await load();setMessage('Default address updated.')}catch{setError('Unable to update default address.')}}
  async function remove(id:string){if(!window.confirm('Delete this saved address?'))return;setError('');try{const r=await fetch('/api/account/addresses',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to delete address.');return;}if(editing===id)reset();await load();setMessage('Address deleted.')}catch{setError('Unable to delete address.')}}
  const input=(key:keyof typeof empty,label:string,required=false)=><label className="block text-xs font-black text-slate-700">{label}<input required={required} value={String(form[key]??'')} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm text-slate-900 outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-500/10"/></label>;
  return <main className="min-h-screen bg-[#f7f8fc] text-slate-900"><header className="border-b border-slate-200 bg-white/90 backdrop-blur"><div className="container flex h-16 items-center justify-between"><Link href="/" className="brand-mark text-2xl font-black">Zenvora<span className="text-fuchsia-500">.</span></Link><Link href="/account" className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-slate-600 hover:border-violet-300 hover:text-violet-700">← My account</Link></div></header>
  <div className="container py-8 sm:py-12"><div className="mb-7"><p className="text-[10px] font-black uppercase tracking-[.2em] text-fuchsia-600">Delivery</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Saved addresses</h1><p className="mt-2 text-sm text-slate-500">Keep your delivery details ready for checkout.</p></div>
  <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-xl shadow-violet-950/5 sm:p-7"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-black">Your addresses</h2><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-black text-violet-700">{addresses.length} saved</span></div>
  {loading?<p className="mt-7 text-slate-500">Loading addresses…</p>:addresses.length===0?<div className="mt-7 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-8 text-center text-sm text-slate-500">No saved addresses yet. Add your first delivery address.</div>:<div className="mt-6 space-y-3">{addresses.map(a=><article key={a.id} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4 transition hover:border-violet-200 hover:bg-violet-50/40"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-900">{a.label}</h3>{a.isDefault&&<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">Default</span>}</div><p className="mt-3 text-sm font-black">{a.fullName}</p><p className="mt-1 text-xs text-slate-500">{a.phone}</p><p className="mt-3 text-xs leading-5 text-slate-600">{[a.addressLine1,a.addressLine2,a.landmark].filter(Boolean).join(', ')}<br/>{a.city}, {a.district}, {a.state} — {a.pinCode}</p></div><div className="flex shrink-0 flex-col gap-2"><button onClick={()=>edit(a)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-black text-slate-600 hover:border-violet-200 hover:text-violet-700">Edit</button><button onClick={()=>remove(a.id)} className="rounded-xl border border-rose-100 bg-white px-3 py-2 text-xs font-black text-rose-600 hover:bg-rose-50">Delete</button></div></div>{!a.isDefault&&<button onClick={()=>makeDefault(a.id)} className="mt-4 text-xs font-black text-violet-700">Set as default →</button>}</article>)}</div>}
  </section>
  <section className="h-fit rounded-[28px] border border-slate-200 bg-white p-5 shadow-xl shadow-violet-950/5 sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.2em] text-fuchsia-600">{editing?'Edit address':'Add address'}</p><h2 className="mt-2 text-2xl font-black">{editing?'Update delivery address':'New delivery address'}</h2><form onSubmit={save} className="mt-6 space-y-3">{input('label','Label',true)}{input('fullName','Full name',true)}{input('phone','Mobile number',true)}{input('addressLine1','Address line 1',true)}{input('addressLine2','Address line 2')}{input('landmark','Landmark')}{input('city','City',true)}{input('district','District',true)}{input('state','State',true)}{input('pinCode','PIN code',true)}<label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-700"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Set as default address</label>{error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs font-bold text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-700">{message}</div>}<button disabled={saving} className="h-12 w-full rounded-xl bg-gradient-to-r from-violet-700 to-fuchsia-500 font-black text-white shadow-lg shadow-violet-500/20 disabled:opacity-60">{saving?'Saving…':editing?'Update address':'Save address →'}</button>{editing&&<button type="button" onClick={reset} className="h-11 w-full rounded-xl border border-slate-200 bg-white font-bold text-slate-600">Cancel editing</button>}</form></section>
  </div></div></main>;
}
