'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Address={id:string;label:string;fullName:string;phone:string;addressLine1:string;addressLine2:string|null;landmark:string|null;city:string;district:string;state:string;pinCode:string;isDefault:boolean};
const empty={label:'Home',fullName:'',phone:'',addressLine1:'',addressLine2:'',landmark:'',city:'',district:'',state:'',pinCode:'',isDefault:false};

export default function Addresses(){
  const [addresses,setAddresses]=useState<Address[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  async function load(){try{const r=await fetch('/api/account/addresses');const d=await r.json();if(!r.ok){setError(d.error||'Unable to load addresses.');return;}setAddresses(d.addresses||[]);}catch{setError('Unable to load addresses.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  function edit(a:Address){setEditing(a.id);setForm({...a,addressLine2:a.addressLine2||'',landmark:a.landmark||''});setError('');setMessage('');window.scrollTo({top:0,behavior:'smooth'});}
  function reset(){setEditing(null);setForm({...empty,isDefault:addresses.length===0});setError('');}
  async function save(e:React.FormEvent){e.preventDefault();setError('');setMessage('');setSaving(true);try{const r=await fetch('/api/account/addresses',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{...form,id:editing}:form)});const d=await r.json();if(!r.ok){setError(d.error||'Unable to save address.');return;}await load();reset();setMessage(editing?'Address updated successfully.':'Address saved successfully.');}catch{setError('Unable to save address.');}finally{setSaving(false);}}
  async function makeDefault(id:string){setError('');try{const a=addresses.find(x=>x.id===id);if(!a)return;const r=await fetch('/api/account/addresses',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,isDefault:true})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to set default address.');return;}await load();setMessage('Default address updated.');}catch{setError('Unable to update default address.');}}
  async function remove(id:string){if(!window.confirm('Delete this saved address?'))return;setError('');try{const r=await fetch('/api/account/addresses',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to delete address.');return;}if(editing===id)reset();await load();setMessage('Address deleted.');}catch{setError('Unable to delete address.');}}
  const input=(key:keyof typeof empty,label:string,required=false)=><label className="block text-sm font-bold text-slate-200">{label}<input required={required} value={String(form[key]??'')} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/5 px-4 text-white outline-none focus:border-violet-500" /></label>;
  return <main className="min-h-screen bg-[#070b16] text-white"><header className="border-b border-white/10 bg-[#090e1c]/90"><div className="container flex h-16 items-center justify-between"><Link href="/" className="text-2xl font-black">🛍️ Zenvora<span className="text-fuchsia-400">.</span></Link><Link href="/account" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold text-slate-300">← My account</Link></div></header>
  <div className="container py-8 sm:py-12"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]">
    <section className="rounded-3xl border border-white/10 bg-white/5 p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-fuchsia-400">Delivery</p><h1 className="mt-2 text-3xl font-black">Saved addresses</h1><p className="mt-2 text-sm text-slate-400">Keep your delivery details ready for checkout.</p></div><span className="rounded-full bg-violet-500/15 px-3 py-1 text-xs font-bold text-violet-200">{addresses.length} saved</span></div>
      {loading?<p className="mt-8 text-slate-400">Loading addresses…</p>:addresses.length===0?<div className="mt-8 rounded-2xl border border-dashed border-white/10 p-8 text-center text-slate-400">No saved addresses yet. Add your first delivery address.</div>:<div className="mt-7 space-y-4">{addresses.map(a=><article key={a.id} className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{a.label}</h2>{a.isDefault&&<span className="rounded-full bg-emerald-500/15 px-2.5 py-1 text-[11px] font-bold text-emerald-300">Default</span>}</div><p className="mt-3 font-bold">{a.fullName}</p><p className="mt-1 text-sm text-slate-300">{a.phone}</p><p className="mt-3 text-sm leading-6 text-slate-400">{[a.addressLine1,a.addressLine2,a.landmark].filter(Boolean).join(', ')}<br/>{a.city}, {a.district}, {a.state} — {a.pinCode}</p></div><div className="flex shrink-0 flex-col gap-2"><button onClick={()=>edit(a)} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-slate-300 hover:bg-white/5">Edit</button><button onClick={()=>remove(a.id)} className="rounded-xl border border-red-400/10 px-3 py-2 text-xs font-bold text-red-300 hover:bg-red-500/10">Delete</button></div></div>{!a.isDefault&&<button onClick={()=>makeDefault(a.id)} className="mt-4 text-xs font-black text-fuchsia-400">Set as default →</button>}</article>)}</div>}
    </section>
    <section className="h-fit rounded-3xl border border-white/10 bg-white/5 p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-widest text-fuchsia-400">{editing?'Edit address':'Add address'}</p><h2 className="mt-2 text-2xl font-black">{editing?'Update delivery address':'New delivery address'}</h2><form onSubmit={save} className="mt-6 space-y-4">{input('label','Label',true)}{input('fullName','Full name',true)}{input('phone','Mobile number',true)}{input('addressLine1','Address line 1',true)}{input('addressLine2','Address line 2')}{input('landmark','Landmark')}{input('city','City',true)}{input('district','District',true)}{input('state','State',true)}{input('pinCode','PIN code',true)}<label className="flex items-center gap-3 rounded-xl bg-black/20 p-3 text-sm font-bold"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Set as default address</label>{error&&<div role="alert" className="rounded-xl border border-red-400/20 bg-red-500/10 px-4 py-3 text-sm font-semibold text-red-300">{error}</div>}{message&&<div className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 px-4 py-3 text-sm font-semibold text-emerald-300">{message}</div>}<button disabled={saving} className="h-12 w-full rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-500 font-black disabled:opacity-60">{saving?'Saving…':editing?'Update address':'Save address'}</button>{editing&&<button type="button" onClick={reset} className="h-11 w-full rounded-xl border border-white/10 font-bold text-slate-300">Cancel editing</button>}</form></section>
  </div></div></main>;
}
