import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '../../../auth';
import { db } from '../../../lib/db';

export default async function Dashboard(){
 const session=await auth(); if(!session?.user?.email)redirect('/admin/login');
 const [orders,pending,confirmed,shipped,products]=await Promise.all([db.order.count(),db.order.count({where:{status:'PAYMENT_PENDING'}}),db.order.count({where:{status:'CONFIRMED'}}),db.order.count({where:{status:'SHIPPED'}}),db.product.count()]);
 return <main className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="container flex min-h-16 flex-wrap items-center justify-between gap-3 py-3"><Link href="/" className="text-xl font-black">zenvora<span className="text-indigo-600">.</span></Link><nav className="flex items-center gap-1 text-sm font-bold"><Link href="/admin/dashboard" className="rounded-lg bg-slate-100 px-3 py-2">Dashboard</Link><Link href="/admin/products" className="rounded-lg px-3 py-2 hover:bg-slate-100">Products</Link><Link href="/admin/orders" className="rounded-lg px-3 py-2 hover:bg-slate-100">Orders</Link><Link href="/admin/settings" className="rounded-lg px-3 py-2 hover:bg-slate-100">Settings</Link><Link href="/" className="ml-1 rounded-lg bg-slate-950 px-3 py-2 text-white">Store</Link></nav></div></header><div className="container py-8 md:py-10"><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Admin panel</p><h1 className="mt-1 text-3xl font-black tracking-tight">Store dashboard</h1><p className="mt-2 text-slate-500">Welcome, {session.user.email}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Products',products],['Total orders',orders],['Pending payment',pending],['Confirmed',confirmed],['Shipped',shipped]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div><div className="mt-8 grid gap-5 md:grid-cols-3"><Link href="/admin/products" className="rounded-2xl bg-slate-950 p-6 text-white transition hover:-translate-y-0.5"><p className="text-sm font-bold text-slate-300">Catalog</p><h2 className="mt-1 text-xl font-black">Manage products →</h2><p className="mt-2 text-sm text-slate-300">Add products, prices, stock and categories.</p></Link><Link href="/admin/orders" className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5"><p className="text-sm font-bold text-indigo-600">Operations</p><h2 className="mt-1 text-xl font-black">Manage orders →</h2><p className="mt-2 text-sm text-slate-500">Review payments and update fulfillment.</p></Link><Link href="/admin/settings" className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5"><p className="text-sm font-bold text-indigo-600">Payments</p><h2 className="mt-1 text-xl font-black">Payment settings →</h2><p className="mt-2 text-sm text-slate-500">Configure Razorpay settings.</p></Link></div></div></main>;
}