import Link from 'next/link';
import AdminNav from '../../../components/admin-nav';
import { redirect } from 'next/navigation';
import { auth } from '../../../auth';
import { db } from '../../../lib/db';

export default async function Dashboard(){
 const session=await auth(); if(session?.user?.role!=='admin')redirect('/admin/login');
 const [orders,pending,confirmed,shipped,products,lowStock,revenue]=await Promise.all([db.order.count(),db.order.count({where:{status:'PAYMENT_PENDING'}}),db.order.count({where:{status:'CONFIRMED'}}),db.order.count({where:{status:'SHIPPED'}}),db.product.count(),db.product.count({where:{status:'ACTIVE',stock:{lte:5}}}),db.order.aggregate({where:{status:{in:['CONFIRMED','ORDERED_FROM_SOURCE','SHIPPED','DELIVERED']}},_sum:{totalAmount:true}})]);
 return <main className="min-h-screen bg-slate-100"><AdminNav active="dashboard"/><div className="container py-8 md:py-10"><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Admin panel</p><h1 className="mt-1 text-3xl font-black tracking-tight">Store dashboard</h1><p className="mt-2 text-slate-500">Welcome, {session.user.email}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{[['Products',products],['Total orders',orders],['Pending payment',pending],['Confirmed',confirmed],['Shipped',shipped]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div><div className="mt-8 grid gap-5 md:grid-cols-3"><Link href="/admin/products" className="rounded-2xl bg-slate-950 p-6 text-white transition hover:-translate-y-0.5"><p className="text-sm font-bold text-slate-300">Catalog</p><h2 className="mt-1 text-xl font-black">Manage products →</h2><p className="mt-2 text-sm text-slate-300">Add products, prices, stock and categories.</p></Link><Link href="/admin/orders" className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5"><p className="text-sm font-bold text-indigo-600">Operations</p><h2 className="mt-1 text-xl font-black">Manage orders →</h2><p className="mt-2 text-sm text-slate-500">Review payments and update fulfillment.</p></Link><Link href="/admin/settings" className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5"><p className="text-sm font-bold text-indigo-600">Payments</p><h2 className="mt-1 text-xl font-black">Payment settings →</h2><p className="mt-2 text-sm text-slate-500">Configure Razorpay settings.</p></Link></div></div></main>;
}