import Link from 'next/link';
import { db } from '../../lib/db';

export default async function Products({ searchParams }: { searchParams: { q?: string; sort?: string; page?: string } }) {
  const page = Math.max(1, Number(searchParams.page || 1) || 1);
  const size = 12;
  const q = searchParams.q?.trim();
  const where = { status:'ACTIVE' as const, ...(q ? { OR:[{name:{contains:q,mode:'insensitive' as const}},{description:{contains:q,mode:'insensitive' as const}},{category:{name:{contains:q,mode:'insensitive' as const}}}] } : {}) };
  const orderBy = searchParams.sort==='price-asc'?{sellingPrice:'asc' as const}:searchParams.sort==='price-desc'?{sellingPrice:'desc' as const}:{createdAt:'desc' as const};
  const [items,count]=await Promise.all([
    db.product.findMany({where,orderBy,skip:(page-1)*size,take:size,select:{id:true,name:true,slug:true,sellingPrice:true,stock:true,images:{orderBy:{sortOrder:'asc'},take:1,select:{url:true,altText:true}}}}),
    db.product.count({where})
  ]);
  const pages=Math.ceil(count/size);
  return <main className="min-h-screen bg-[#070b16] text-white">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#070b16]/90 backdrop-blur-xl"><div className="container flex h-16 items-center gap-4"><Link href="/" className="shrink-0 text-2xl font-black">🛍️ Zenvora<span className="text-fuchsia-400">.</span></Link><form className="hidden flex-1 md:block"><input name="q" defaultValue={q} placeholder="Search products..." className="h-11 w-full rounded-2xl border border-white/10 bg-white/5 px-5 text-sm outline-none placeholder:text-slate-500 focus:border-violet-500"/></form><nav className="hidden gap-5 text-sm font-bold text-slate-300 lg:flex"><Link href="/products">Shop</Link><Link href="/track">Track Order</Link></nav><div className="ml-auto flex items-center gap-2"><Link href="/login" className="hidden rounded-xl border border-white/10 px-3 py-2 text-sm font-bold sm:inline-flex">Login</Link><Link href="/signup" className="rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-500 px-3 py-2 text-sm font-black">Sign Up</Link><Link href="/cart" className="px-2 text-xl">🛒</Link></div></div></header>
    <div className="container py-10 sm:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.22em] text-fuchsia-400">Premium products</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Discover your next find</h1><p className="mt-3 text-sm text-slate-400">{count} products available</p></div><form className="flex gap-2"><input name="q" defaultValue={q} placeholder="Search..." className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none placeholder:text-slate-500 sm:w-56"/><select name="sort" defaultValue={searchParams.sort||''} className="rounded-xl border border-white/10 bg-[#101729] px-3 py-3 text-sm outline-none"><option value="">Newest</option><option value="price-asc">Price low → high</option><option value="price-desc">Price high → low</option></select><button className="rounded-xl bg-white px-4 py-3 font-black text-slate-950">Go</button></form></div>
    {items.length===0?<div className="py-24 text-center text-slate-500">No products found.</div>:<div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(p=><Link key={p.id} href={`/product/${p.slug}`} className="group overflow-hidden rounded-3xl border border-white/10 bg-white/5 transition hover:-translate-y-1 hover:border-violet-400/40"><div className="flex h-60 items-center justify-center overflow-hidden bg-gradient-to-br from-white/5 to-violet-900/20">{p.images[0]?<img src={p.images[0].url} alt={p.images[0].altText||p.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<span className="text-7xl">🛍️</span>}</div><div className="p-5"><h2 className="line-clamp-2 min-h-12 font-bold">{p.name}</h2><p className="mt-3 text-xl font-black">₹{Number(p.sellingPrice).toLocaleString('en-IN',{minimumFractionDigits:2})}</p><p className="mt-1 text-xs text-slate-500">{p.stock>0?'In stock':'Out of stock'}</p><span className="mt-4 inline-flex rounded-xl bg-violet-600/15 px-3 py-2 text-xs font-bold text-violet-200">View product →</span></div></Link>)}</div>}
    {pages>1&&<div className="mt-10 flex flex-wrap justify-center gap-2">{Array.from({length:pages},(_,i)=>i+1).map(n=>{const params=new URLSearchParams();if(q)params.set('q',q);if(searchParams.sort)params.set('sort',searchParams.sort);params.set('page',String(n));return <Link key={n} href={`/products?${params.toString()}`} className={`rounded-xl px-4 py-2 text-sm font-bold ${n===page?'bg-violet-600 text-white':'bg-white/5 text-slate-300'}`}>{n}</Link>})}</div>}
    </div>
  </main>;
}
